version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app 
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    networks:
      - flask_network

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/swagger.json
    volumes:
      - .:/app 
      - ./swagger.json:/swagger.json:ro
    networks:
      - flask_network

networks:
  flask_network:
